### ISSUE TITLE
Modeline lighter displays an abnormality after configuring the modeline lighter

### ISSUE THREAD

**Issue by re-mx** [bbatsov/projectile#1287]
## Expected behavior

Modeline lighter is normal

## Actual behavior

See this:
<img width="1280" alt="2018-09-22 7 55 16" src="https://user-images.githubusercontent.com/26828933/45910582-e3904c00-be3c-11e8-9e8d-b17c5081d015.png">

## Steps to reproduce the problem

configure projectile like this:
```emacs-lisp
(projectile-mode 1)
(with-eval-after-load 'projectile
    ;; Shorter modeline
    (setq-default
     projectile-mode-line
     '(:eval
       (if (file-remote-p default-directory)
           " Proj"
         (format " Proj[%s]" (projectile-project-name))))))
```

### Projectile version information

```
Projectile 20180921.1552
```

### Emacs version

```
GNU Emacs 26.1
```
### Operating system

Arch Linux @ Linux 4.18.9

**Comment by re-mx** [comment]
BTW: Even if projectile-mode-line is not configured, the modeline lighter display is not normal.

<img width="1280" alt="2018-09-22 8 07 17" src="https://user-images.githubusercontent.com/26828933/45910913-cf018300-be3f-11e8-808b-8b73af423599.png">
<img width="1280" alt="2018-09-22 8 05 42" src="https://user-images.githubusercontent.com/26828933/45910922-da54ae80-be3f-11e8-9313-8ff700451454.png">

**Comment by dcreemer** [comment]
I believe this change:
https://github.com/bbatsov/projectile/blob/bbca83fce64007e710dd0bc2a1932b9410de1b66/projectile.el#L3888-L3890

causes the modeline to grow on each project switch (since it's adding the previous `projectile-mode-line` into the formatting of the new `projectile-mode-line`

**Comment by re-mx** [comment]
But this will cause the modeline for people who don't use a custom modeline to grow longer and longer as the number of projects open at the same time increases.

And at least, I think you forgot a space:
<img width="195" alt="2018-09-22 12 31 46" src="https://user-images.githubusercontent.com/26828933/45913370-9d9aae80-be63-11e8-9fb2-f1f0f4fba025.png">

**Comment by bbatsov** [comment]
> But this will cause the modeline for people who don't use a custom modeline to grow longer and longer as the number of projects open at the same time increases.

Longer? It's just one project all the time. It can't grow longer than this.

Yep, seems I forgot the space indeed.

**Comment by re-mx** [comment]
The "normal" I defined is the same as the original showing only the project where the currently open file is located. 

But I am sorry if the implementation of "Show only current project" is difficult due to this new feature (showing project-type).

At least for me, every time a newly opened project is added to the modelline instead of being replaced.

... I will try to reinstall my Emacs configuration. Please don't close this issue, thank you.

**Comment by bbatsov** [comment]
Ops, I just noticed what you mean. I did a retarded mistake.

**Comment by re-mx** [comment]
Don't blame you, I'm sorry for my poor English. I can only speak English by Google Translate...

By the way, is there a way to set "projectile" to "Proj"? Thanks.

**Comment by re-mx** [comment]
Thanks.

**Comment by bbatsov** [comment]
```
(setq projectile-mode-line-lighter " Proj")
```

**Comment by bbatsov** [comment]
> In the non-file buffer and remote file buffer, even "Projectile" itself is not displayed?

Fixed. 

> And I think it's necessary to display the project-name in dired-mode.

Why so? After all there you see the directory tree anyways.

**Comment by re-mx** [comment]
@bbatsov 
There is still a problem here, only if I set `projectile-mode-line-lighter` before `projectile-mode` is loading, `projectile-mode-line-lighter` will take effect in the non-file buffers and the remote buffers.
